name: Deploy Travel Planner Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project with Maven
        run: mvn clean package -DskipTests --no-transfer-progress

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tripguru-backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tripguru-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tripguru-backend:latest
            docker stop tripguru-backend || true
            docker rm tripguru-backend || true
            docker run -d --pull always \
              --name tripguru-backend \
              --restart unless-stopped \
              -p 8080:8080 \
              --env-file /home/${{ secrets.VPS_USER }}/tripguru.env \
              ${{ secrets.DOCKER_USERNAME }}/tripguru-backend:latest
            docker logs --tail=20 tripguru-backend
